### PR TITLE
Coordinate Boundary Analysis

### PR DESCRIPTION
**Pull request by kschutt**
Add the ability to fetch and store coordinates in doubles instead of
ints. Also, check the boundaries of those coordinates to ensure they are
correct. Borrowed lovingly from Scott Schluer.

### CODE REVIEW

**Comment by meebey** [comment]
What is the advantage of double over ints and why should this be included in Twitterizer? The licensing of the included code is uncertain btw.

**Comment by kschutt** [comment]
Doubles provide a higher level of precision for the GPS coordinates. As per the Twitter API, coordinates are represented as such. Float could also work.

**Comment by kschutt** [comment]
Also, to reply to your licensing question. Please see his response: https://github.com/scottschluer/geolocation/issues/2

**Comment by jamiehowarth0** [comment]
Licensing is fine, both projects are MIT. Will review this.

**Comment by DigitallyBorn** [comment]
I don't think this functionality should be included within Twitterizer for two reasons:
1. It is not our core business (handling communication with the Twitter API)
2. Pulling it into the project will require us to maintain it.

**Comment by DigitallyBorn** [comment]
Does anyone disagree? If not, I will close.

**Comment by meebey** [comment]
Am 20.11.2014 21:14 schrieb "Ricky Smith" notifications@github.com:

> Does anyone disagree? If not, I will close.

I agree that this is out-of-scope for a Twitter lib

**Pull request closed without merging**
